config/routes.rb
Halftime::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :schedules, :only => [:new, :index, :edit, :show, :create, :destroy, :update] do
    resources :events, :shallow => true
  end

  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'

  root                :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :schedules, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
                    :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..40 },
                        :if => :password_changed?

  before_save :encrypt_password

  # Return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def password_changed?
      !@password.blank? or encrypted_password.blank?
    end

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate,      :only => [:index, :show, :edit, :update, :destroy]
  before_filter :correct_or_admin,  :only => [:show, :edit, :update]
  before_filter :admin_user,        :only => [:index, :destroy]

  def new
    @user = User.new
    @title = "sign up"
  end

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page], :per_page => params[:per_page])
  end

  def show
    @user = User.find(params[:id])
    @schedules = @user.schedules.paginate(:page => params[:page])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to halftime!"
      redirect_to @user
    else
      @title = "sign up"
      render 'new'
    end
  end

  def edit
    @title = "Edit user"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:succcess] = "User destroyed."
    redirect_to users_path
  end

  private

  def correct_or_admin
    @user = User.find(params[:id])
    redirect_to(root_path) unless (current_user.admin? or current_user?(@user))
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? %>
	| <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
																:title => "Delete #{user.name}"%>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
			<% unless @user.schedules.empty? %>
				<table class="schedules" summary="User schedules">
					<%= render @schedules %>
			 	</table>
				<%= will_paginate @schedules %>
			<% end %>
		</td>
		<td class="sidebar round">
			<strong>Name</strong> <%= @user.name %> <br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %> <br />
			<strong>Schedules</strong> <%= @user.schedules.count %>
		</td>
	</tr>
</table>