config/routes.rb
Halftime::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :schedules, :only => [:new, :index, :edit, :show, :create, :destroy, :update] do
    resources :events, :shallow => true
  end

  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'

  root                :to => 'pages#home'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :title
  has_many :events, :dependent => :destroy
  belongs_to :user
  
  validates :title, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true
  
  default_scope :order => 'schedules.created_at DESC'
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :authenticate
  before_filter :correct_user, :only => [:show, :edit, :update, :destroy]
  
  def new
    @schedule = Schedule.new()
    @title = "New Schedule"
  end
  
  def index
    @title = "Your Schedules"
    @schedules = current_user.schedules.paginate(:page => params[:page])
  end
  
  def show
    @schedule = Schedule.find(params[:id])
    @title = @schedule.title
    @events = @schedule.events.paginate(:page => params[:page], :per_page => 10)
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update_attributes(params[:schedule])
      flash[:success] = "Schedule updated."
      redirect_to @schedule
    else
      @title = "Edit schedule"
      render 'edit'
    end
  end
  
  def create
    @schedule = current_user.schedules.build(params[:schedule])
    if @schedule.save
      flash[:success] = "Schedule Created!"
      redirect_to @schedule
    else
      flash[:error] = "Error creating schedule."
      render 'new'
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    if @schedule.destroy
      flash[:success] = "Schedule Deleted!"
        redirect_to :action =>  :index
    else
      flash[:error] = "Error deleting schedule."
      render @schedule
    end
    
  end
  
  private
  
  
  def correct_user
    @schedule = Schedule.find(params[:id])
    unless current_user.id == @schedule.user_id
      redirect_to(root_path)
    end
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_schedule.html.erb
<tr>
	<td class="schedule">
		<span class="title"><%= link_to schedule.title, schedule %></span>
		<span class="timestamp">
			Created <%= time_ago_in_words(schedule.created_at) %> ago.
		</span>
	</td>
</tr>

app/views/schedules/_schedule_form.html.erb
<%= form_for @schedule do |s| %>
	<%= render 'shared/error_messages', :object => s.object %>
	<div class="field">
		<%= s.label :title %>
		<%= s.text_field :title %>
	</div>
	<div class="actions">
		<%= s.submit "Submit" %>
	</div>
<% end %>	

app/views/schedules/edit.html.erb
<h1>Edit schedule</h1>

<%= form_for(@schedule) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/schedules/index.html.erb
<h1>Your Schedules</h1>

<%= will_paginate %>

<ul class="schedules">
	<% @schedules.each do |schedule| %>
		<li>
			<%= link_to schedule.title, schedule %> | <%= link_to "Edit", edit_schedule_path(schedule) %> | <%= link_to "Delete", @schedule, :method => :delete, :confirm => "Are you sure you would like to delete this schedule?"%>
		</li>
	<% end %>
</ul>

<%= link_to "New Schedule", new_schedule_path %>

<%= will_paginate %>

app/views/schedules/new.html.erb
<h1>Create a new Schedule:</h1>
<%= render 'schedules/schedule_form' %>

app/views/schedules/show.html.erb
<table class="profile" summary="Profile Information">
	<tr>
		<td class="main">
			<h1>
				<%= @schedule.title %>
			</h1>
			<%= pluralize(@events.count, "event") %> 
			<% unless @events.empty? %>
				<table class="events" summary="Schedule events">
					<%= render @events %>
			 	</table>
				<%= will_paginate @events %>
			<% end %>
			<ul>
				<li><%= link_to "Add Event", new_schedule_event_path(@schedule) %></li>
			</ul>
		</td>
	</tr>
</table>