config/routes.rb
Halftime::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :schedules, :only => [:new, :index, :edit, :show, :create, :destroy, :update] do
    resources :events, :shallow => true
  end

  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'

  root                :to => 'pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :occursAt
  
  belongs_to :schedule
  
  validates :description, :presence => true, :length => { :maximum => 140 }
  validates :schedule_id, :presence => true
  validates :occursAt, :presence => true
  
  default_scope :order => 'events.occursAt ASC'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate
  before_filter :correct_user

  def new
    @title = "New Event"
    @event = Event.new
  end

  def index
    @schedule = Schedule.find(params[:schedule_id])
    @events = @schedule.events.paginate(:page => params[:page], :per_page => 10)
    @title = "Events for " + @schedule.title
  end

  def create
    @schedule = Schedule.find(params[:schedule_id])
    @event = @schedule.events.build(params[:event])
    if @event.save
      flash[:success] = "Event Created!"
      redirect_to @schedule
    else
      @title = "New Event"
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @schedule = @event.schedule
    if @event.destroy
      flash[:success] = 'Event Deleted!'
      redirect_to schedule_events_url(@schedule)
    else
      flash[:error] = 'Error deleting schedule.'
      render @event
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:success] = "Event updated."
      redirect_to @event
    else
      flash[:failure] = "Update failed."
      @title = "Edit event"
      render 'edit'
    end

  end

  private

  def authenticate
    deny_access unless signed_in?
  end

  def correct_user
    #check needed because of shallow nesting resource routes
    if params.has_key?(:schedule_id) then
      @schedule = Schedule.find(params[:schedule_id])
    else
      @schedule = Event.find(params[:id]).schedule
    end
    redirect_to(root_path) unless current_user?(@schedule.user)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<tr>
	<td class="event">
		<span class="description"><%= link_to( event.description, event_path(event)) %></span>
		<span class="timestamp">
			Occurs in: <%= distance_of_time_in_words_to_now(event.occursAt) %>.
		</span>
	</td>
</tr>

app/views/events/_event_form.html.erb
<%= form_for [:schedule, @event] do |e| %>
	<%= render 'shared/error_messages', :object => e.object %>
	<div class="field">
		<%= e.label :description %>
		<%= e.text_field :description %>
	</div>
	<div class="field">
		<%= e.label :occursAt %>
		<%= e.datetime_select :occursAt %>
	</div>
	<div class="action">
		<%= e.submit "Submit" %>
	</div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= form_for([@event]) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :occursAt %><br />
      <%= f.datetime_select :occursAt %>
    </div>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>

app/views/events/index.html.erb
<h1>Your Events for Schedule: <%= @schedule.title %></h1>

<%= will_paginate %>

<ul class="events">
  <% @events.each do |event| %>
      <li>
        <%= link_to event.description, event, :class => "description" %>
        <span class="timestamp">Occurs: <%= time_ago_in_words(event.occursAt) %> ago.</span>
        | <%= link_to "Edit", edit_schedule_event_path(@schedule, event) %>
        | <%= button_to "Delete", event, :method => :delete, :confirm => "Are you sure you would like to delete this event?"%>
      </li>
  <% end %>
</ul>

<%= link_to "New Event", new_schedule_event_path(@schedule) %>

<%= will_paginate %>

app/views/events/new.html.erb
<h1>Create an Event</h1>
<%= render 'events/event_form' %>

app/views/events/show.html.erb
<div>
  <span>Schedule: <%= @event.schedule.title %></span>
  <h1>Event: <span class="description"><%= @event.description %></span></h1>
  <span><%= @event.occursAt %></span>
  <%= button_to "Delete", @event, :method => :delete %>
</div>